Repository bidiac-de/etl-core, pull requests merged in 2025-07, with the labels that each got.

#25 #3 introduce source code file structure
  .github/workflows/build.yml
  .gitignore
  README.md
  docs/documentation.md
  requirements.txt
  sonar-project.properties
  src/api/main.py
  src/components/base.py
  src/components/data_operations/data_operations.py
  src/components/databases/database.py
  src/components/databases/mariadb/mariadb.py
  src/components/databases/mariadb/mariadb_read.py
  src/components/databases/mariadb/mariadb_write.py
  src/config/api_config.yaml
  src/handler/job_execution_handler.py
  src/receivers/base.py
  src/receivers/dataOperations_receiver.py
  src/receivers/databases/mariadb_receiver.py
  src/receivers/read_receiver.py
  src/receivers/write_receiver.py
  src/strategies/base_strategy.py
  src/strategies/bigdata_strategy.py
  src/strategies/bulk_strategy.py
  src/strategies/row_strategy.py
  tests/test_init.py
Labels: enhancement

#30 Staging
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/flake8.yml
  .github/workflows/tests.yml
  requirements.txt
  sonar-project.properties
Labels: documentation, enhancement

#34 Add permissions section to SonarQube workflow for enhanced access con…
  .github/workflows/build.yml
Labels: bug
